name: Get Contributors with Images

on: 
  workflow_dispatch:

jobs:
  get-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v4
        with:
          script: |
            const contributors = github.rest.repos.listContributors({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            // Process contributor data and download images
      - name: Store output
        uses: actions/upload-artifact@v3
        with:
          name: contributors-images
          path: contributors-images
